#!/usr/bin/env python

#multi_agent.py
#
#by Joe Hahn
#jmh.datasciences@gmail.com
#10 February 2018
#
#helper functions for an experiment with Q-learning on system having multiple agents 

#imports
import numpy as np
import pandas as pd
import random
import copy
from collections import deque

#initialize the environment = dict containing all constants that describe the system
def initialize_environment(rn_seed, max_turns, N_buckets, N_agents):
    random.seed(rn_seed)
    actions = np.arange(N_buckets)
    acts = ['move to ' + str(action) for action in actions]
    p0 = np.linspace(0.5, 1.5, num=N_buckets)
    sigma = np.linspace(0.25, 3.0, num=N_buckets)
    bucket_params = {'p0':p0, 'sigma':sigma}
    environment = {'rn_seed':rn_seed, 'max_turns':max_turns, 'N_buckets':N_buckets,
        'N_agents':N_agents, 'bucket_params':bucket_params, 'actions':actions, 'acts':acts}
    return environment

#initial state
def initialize_state(environment):
    N_buckets = environment['N_buckets']
    N_agents = environment['N_agents']
    bucket_params = environment['bucket_params']
    actions = environment['actions']
    agent_locations = np.random.choice(actions, size=N_agents, replace=False)
    state = {'agent_locations':agent_locations}
    agent_health = np.zeros(N_agents) + 1.0
    state['agent_health'] = agent_health
    state['bucket_productivity'] = bucket_productivity(environment)
    state['previous_bucket_productivity'] = bucket_productivity(environment)
    return state

#increment time and update bucket rewards
def bucket_productivity(environment):
    p0 = environment['bucket_params']['p0']
    sigma = environment['bucket_params']['sigma']
    bucket_productivity = p0 + np.random.normal(loc=0.0, scale=sigma)
    return bucket_productivity

#reward = sum of rewards generated by all occupied buckets
def get_reward(state):
    agent_locations = state['agent_locations']
    agent_health = state['agent_health']
    bucket_productivity = state['bucket_productivity']
    reward = (agent_health*bucket_productivity[agent_locations]).sum()
    return reward

#convert state into a numpy array agent locations
def state2vector(state, environment):
    N_agents = environment['N_agents']
    N_buckets = environment['N_buckets']
    agent_locations = state['agent_locations']
    locations = np.zeros(N_buckets)
    for idx in range(N_agents):
        loc = agent_locations[idx]
        locations[loc] += 1.0
    previous_bucket_productivity = state['previous_bucket_productivity']
    v = np.concatenate([locations, previous_bucket_productivity]).reshape(1, 2*N_buckets)
    return v

#move agent
def move_agent(state, new_locations):
    state_next = copy.deepcopy(state)
    state_next['agent_locations'] = new_locations
    return state_next

#check game state = running, or too many moves
def get_game_state(turn, environment):
    game_state = 'running'
    max_turns = environment['max_turns']
    if (turn >= max_turns):
        game_state = 'max_turns'
    return game_state

#play one game using indicated strategy
def play_one_game(environment, turn, strategy, model=None):
    state = initialize_state(environment, turn)
    max_turns = environment['max_turns']
    N_buckets = environment['N_buckets']
    N_agents = environment['N_agents']
    memories_list = []
    game_state = get_game_state(turn, environment)
    while (game_state == 'running'):
        #move each agent
        for idx in range(N_agents):
            if (strategy == 'random'):
                action = np.random.choice(environment['actions'])
            if (strategy == 'smart'):
                state_vector = state2vector(state, environment)
                Q = model.predict(state_vector, batch_size=1)
                action = np.argmax(Q)
            state_next = move_agent(state, environment, action)
            reward = get_reward(state_next)
            memory = (turn, state, action, state_next, reward, game_state)
            memories_list += [memory]
            state = copy.deepcopy(state_next)
        #update bucket rewards after all agents have moved
        turn += 1
        state['previous_bucket_rewards'] = state['bucket_rewards']
        state['bucket_rewards'] = get_bucket_rewards(environment, turn)
        game_state = get_game_state(turn, environment)
    N_memories = len(memories_list)
    memories = deque(maxlen=N_memories)
    for memory in memories_list:
        memories.append(memory)
    return memories   

#convert memories queue into timeseries dataframe
def memories2timeseries(memories, environment):
    turns = []
    actions = []
    rewards = []
    bucket_rewards_list = []
    agent_counts_list = []
    N_buckets = environment['N_buckets']
    for memory in memories:
        turn, state, action, state_next, reward, game_state = memory
        turns += [turn]
        actions += [action]
        rewards += [reward]
        bucket_rewards = state['bucket_rewards']
        bucket_rewards_dict = {'reward_'+str(j):bucket_rewards[j] for j in range(len(bucket_rewards))}
        bucket_rewards_list += [bucket_rewards_dict]
        state_vector_next = state2vector(state_next, environment)
        agent_counts_dict = {'agents_'+str(j):state_vector_next[0, j] for j in range(N_buckets)}
        agent_counts_list += [agent_counts_dict]
    d = {'turn':turns, 'action':actions, 'reward':rewards, 'bucket_rewards':bucket_rewards_list,
        'agent_counts':agent_counts_list}
    df = pd.DataFrame(d)
    df = pd.concat([df, df['bucket_rewards'].apply(pd.Series)], axis=1)
    df = pd.concat([df, df['agent_counts'].apply(pd.Series)], axis=1)
    cols = ['turn', 'action', 'reward']
    cols += [col for col in df.columns if ('reward_' in col)]
    cols += [col for col in df.columns if ('agents_' in col)]
    return df[cols]

#generate memories of playing multiple random games
def play_N_games(environment, strategy, N_games):
    memories_list = []
    turn = 0
    N_memories = 0
    for N_game in range(N_games):
        memories = play_one_game(environment, turn, strategy)
        memories_list += [memories]
        N_memories += len(memories)
    memories = deque(maxlen=N_memories)
    for game_memories in memories_list:
        for m in game_memories:
            memories.append(m)
    return memories

#build neural network...change to LSTM network? 
def build_model(N_inputs, N_neurons, N_outputs, dropout_fraction=0.2):
    from keras.models import Sequential
    from keras.layers.core import Dense, Activation, Dropout
    from keras.optimizers import RMSprop
    model = Sequential()
    model.add(Dense(N_neurons, activation='relu', input_shape=(N_inputs,)))
    model.add(Dropout(dropout_fraction))
    model.add(Dense(N_neurons, activation='relu'))
    model.add(Dropout(dropout_fraction))
    #model.add(Dense(N_neurons/2, activation='relu'))
    #model.add(Dropout(dropout_fraction))
    model.add(Dense(N_outputs, activation='linear'))
    rms = RMSprop()
    model.compile(loss='mse', optimizer=rms)
    return model

#train model via Q-learning
def train(environment, model, N_games, gamma, memories, batch_size, debug=False):
    epsilon = 1.0
    rewards = []
    epsilons = []
    games = range(N_games)
    for N_game in games:
        turn = 0
        state = initialize_state(environment, turn)
        state_vector = state2vector(state, environment)
        N_inputs = state_vector.shape[1]
        experience_replay = True
        turn = 0
        #ramp epsilon down
        if (epsilon > 0.15):
            epsilon -= 1.0/(0.33*N_games)
        N_agents = environment['N_agents']
        game_state = get_game_state(turn, environment)
        while (game_state == 'running'):
            #move each agent
            for idx in range(N_agents):
                state_vector = state2vector(state, environment)
                #predict this turn's possible rewards Q
                Q = model.predict(state_vector, batch_size=1)
                #choose best action
                if (np.random.random() < epsilon):
                    #choose random action
                    action = np.random.choice(environment['actions'])
                else:
                    #choose best action
                    action = np.argmax(Q)
                #get next state
                state_next = move_agent(state, environment, action)
                state_vector_next = state2vector(state_next, environment)
                #predict next turn's possible rewards
                Q_next = model.predict(state_vector_next, batch_size=1)
                max_Q_next = np.max(Q_next)
                reward = get_reward(state_next)
                #add next turn's discounted reward to this turn's predicted reward
                Q[0, action] = reward + gamma*max_Q_next
                #add to memory queue
                memory = (turn, state, action, state_next, reward, game_state)
                memories.append(memory)
                #update state
                state = copy.deepcopy(state_next)
            #all agents have moved, so increment turn and update bucket rewards
            turn += 1
            state['previous_bucket_rewards'] = state['bucket_rewards']
            state['bucket_rewards'] = get_bucket_rewards(environment, turn)
            game_state = get_game_state(turn, environment)
            #do experience replay ie train model on batch of randomly selected past experiences
            memories_sub = random.sample(memories, batch_size)
            turnz = [m[0] for m in memories_sub]
            statez = [m[1] for m in memories_sub]
            actionz = [m[2] for m in memories_sub]
            statez_next = [m[3] for m in memories_sub]
            rewardz = [m[4] for m in memories_sub]
            game_statez = [m[5] for m in memories_sub]
            state_vectorz_list = [state2vector(s, environment) for s in statez]
            state_vectorz = np.array(state_vectorz_list).reshape(batch_size, N_inputs)
            Qz = model.predict(state_vectorz, batch_size=batch_size)
            state_vectorz_next_list = [state2vector(s, environment) for s in statez_next]
            state_vectorz_next = np.array(state_vectorz_next_list).reshape(batch_size, N_inputs)
            Qz_next = model.predict(state_vectorz_next, batch_size=batch_size)
            for idx in range(batch_size):
                the_reward = rewardz[idx]
                max_Q_next = np.max(Qz_next[idx])
                the_action = actionz[idx]
                Qz[idx, the_action] = the_reward + gamma*max_Q_next
            model.fit(state_vectorz, Qz, batch_size=batch_size, nb_epoch=1, verbose=0)
        #print something when game ends
        if (debug):
            print '======================='
            print 'game number = ', N_game
            print 'turn = ', turn
            print 'agent_locations = ', state_next['agent_locations']
            print 'reward = ', reward
            print 'epsilon = ', epsilon
            print 'game_state = ', game_state
        else:
            print '.',
        rewards += [reward]
        epsilons += [epsilon]
    return model, np.array(games), np.array(rewards), np.array(epsilons) 
